version: '3'
services:
  node1:
    container_name: node1
    restart: on-failure
    command: ["sleep", "infinity"]
    build:
      dockerfile: "./Dockerfile"
    ports:
      - 2200:22
      - 30777:30777
      - 30779:30779
      - 8080:8080
      - 80:80
      - 443:443
    privileged: true

  node2:
    container_name: node2
    restart: on-failure
    command: ["sleep", "infinity"]
    build:
      dockerfile: "./Dockerfile"
    ports:
      - 2201:22
    privileged: true

  node3:
    container_name: node3
    restart: on-failure
    command: ["sleep", "infinity"]
    build:
      dockerfile: "./Dockerfile"
    ports:
      - 2202:22
    privileged: true

  node4:
    container_name: node4
    restart: on-failure
    command: ["sleep", "infinity"]
    build:
      dockerfile: "./Dockerfile"
    ports:
      - 2203:22
    privileged: true
