apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gitlab
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: gitlab
    spec:
      containers:
        - env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                gitlab_rails['initial_root_password'] = 'adminadmin'
          image: gitlab/gitlab-ee:latest
          name: gitlab-ee
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22
          resources:
            requests:
              memory: "8Gi"
              cpu: "6"
            limits:
              memory: "9Gi"
              cpu: "7"
          volumeMounts:
            - mountPath: /etc/gitlab
              name: gitlab-claim0
            - mountPath: /var/log/gitlab
              name: gitlab-claim1
            - mountPath: /var/opt/gitlab
              name: gitlab-claim2
      hostname: m3learning-gitlab
      restartPolicy: Always
      volumes:
        - name: gitlab-claim0
          persistentVolumeClaim:
            claimName: gitlab-claim0
        - name: gitlab-claim1
          persistentVolumeClaim:
            claimName: gitlab-claim1
        - name: gitlab-claim2
          persistentVolumeClaim:
            claimName: gitlab-claim2
status: {}
