apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-prometheus-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-prometheus  # Add your storage class if not specified
  resources:
    requests:
      storage: 100Gi  # Adjust the storage capacity as needed
